name: vinegar
version: 1.4.1
summary: Vinegar
description: Vinegar
base: core22
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64

slots:
  # for GtkApplication registration
  vinegar:
    interface: dbus
    bus: session
    name: io.github.vinegarhq.Vinegar

package-repositories:
  - type: apt
    url: https://dl.winehq.org/wine-builds/ubuntu/
    suites: [jammy]
    components: [main, universe]
    architectures: [amd64, i386]
    key-id: D43F640145369C51D786DDEA76F1A20FF987672F

parts:
  wine:
    plugin: nil
    stage-packages:
      - winehq-stable

  vinegar:
    source: https://github.com/vinegarhq/vinegar.git
    source-tag: v1.4.1
    plugin: make
    make-parameters:
      - PREFIX=/usr
    build-snaps:
      - go

apps:
  vinegar:
    extensions: [gnome]
    desktop: usr/share/applications/io.github.vinegarhq.Vinegar.app.desktop
    command: usr/bin/vinegar
    common-id: io.github.vinegarhq.Vinegar
    environment:
      HOME: $SNAP_USER_COMMON
    plugs:
      - network
